version: "3.1"

services:

  nginx-image-filter:
    container_name: nginx-image-filter
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 3080:80
    volumes:
      - ./data:/data
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf